# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]
    
    steps:
    - uses: actions/checkout@v6
    - name: Install uv and set the Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true    
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Lint with ruff
      run: | 
        uv run ruff check src tests
    - name: Test with mypy
      run: |
        uv run mypy src
    - name: Test with pytest
      run: |
        uv run pytest --cov=src --cov-report=xml tests
    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.14'  # Only upload from the latest Python production version
      uses: codecov/codecov-action@v6
      with:
        files: ./coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
